### ISSUE TITLE
NERVO - Anywhere You Go (MRVLZ Remix)

### ISSUE THREAD

**Issue by cartert54** [MCatalog/Genres#10]
I'm fairly certain this is not future bass.

**Comment by DylanMorrissey** [comment]
melodic drumstep

**Comment by cartert54** [comment]
Mostrino suggested a pop subgenre (electropop), said it couldn't be future bass nor drumstep because of BPM (200, he says).

**Comment by DylanMorrissey** [comment]
i know it doesn't occur often but dnb and drumstep can definitely be more than 180, even 200
https://www.youtube.com/watch?v=6cN2CWLsEE0
