### ISSUE TITLE
Koven - Everything

### ISSUE THREAD

**Issue by cartert54** [MCatalog/Genres#12]
Previously labeled as future garage...didn't we have it as breaks before the overhaul?

**Comment by DylanMorrissey** [comment]
progressive breaks

**Comment by cartert54** [comment]
isn't prog. breaks a fusion of prog. house and breaks though?

**Comment by DylanMorrissey** [comment]
apparently not

**Comment by Coneboi** [comment]
Progressive breaks seems like a perfect fit for this track

**Comment by ParkAvatarLinked** [comment]
I agree with prog. breaks
