### ISSUE TITLE
Karma Fields - Sweat (Soulji Remix)

### ISSUE THREAD

**Issue by cartert54** [MCatalog/Genres#14]
I highly doubt it's electro industrial since
1. It was a 90's trend
2. It consisted of harsh-sounding lyrics over hard techno beats

Perhaps experimental?

**Comment by Clbsfn** [comment]
Either "Industrial" or "Experimental." I would label it just as Industrial.

**Comment by cartert54** [comment]
That's not an actual trend though...

**Comment by Clbsfn** [comment]
Then just "Industrial."

**Comment by Coneboi** [comment]
Right now, it's listed as Sweet (Soulji Remix). Someone should probably fix that

**Comment by cartert54** [comment]
Whoops
