### ISSUE TITLE
Rogue - Perfect Views

### ISSUE THREAD

**Issue by cartert54** [MCatalog/Genres#2]

**Comment by Clbsfn** [comment]
I've found a youtube video of the song, and the only comments mentioning its genre say that it's trap. It would fit, because the track is 148 BPM and trap music is in the 140s range.

**Comment by cartert54** [comment]
Probably just "trap" as experimental trap is much different than this and hybrid trap is a fusion of trap with heavier styles of EDM (brostep primarily).

**Comment by Clbsfn** [comment]
Okay, then just "trap" would be good.

**Comment by DylanMorrissey** [comment]
future bass

**Comment by Coneboi** [comment]
Actually yeah. Why not future bass?
