### ISSUE TITLE
Karma Fields - Stickup (feat. Juliette Lewis)

### ISSUE THREAD

**Issue by cartert54** [MCatalog/Genres#20]

**Comment by Coneboi** [comment]
Moombahcore

**Comment by DylanMorrissey** [comment]
no complextro or brostep elements

**Comment by Coneboi** [comment]
Moombahcore is just heavy electro. Basically what this is

**Comment by Coneboi** [comment]
Alright. Just electro house then?

**Comment by DylanMorrissey** [comment]
electro-industrial--it's got the harsh vocals

**Comment by Coneboi** [comment]
Electro-industrial has a complex sound, this is very simple

**Comment by cartert54** [comment]
By harsh I mean the sound of the vocals is very harsh on the ears

https://www.youtube.com/watch?v=Zsd5CMzpfys
