### ISSUE TITLE
Fractal - Escape

### ISSUE THREAD

**Issue by cartert54** [MCatalog/Genres#23]

**Comment by Coneboi** [comment]
Liquid drumstep

**Comment by cartert54** [comment]
Not really...it has a more hip hop beat as opposed to a half-time dnb one

I'm thinking glitch hop

**Comment by Coneboi** [comment]
At drumstep tempo?

**Comment by DylanMorrissey** [comment]
yes, glitch-hop can be 87 bpm

**Comment by Coneboi** [comment]
The melody is definitely at 175ish

**Comment by cartert54** [comment]
Forget tempo for a second and listen to the beat

Does that _really_ sound like a drumstep beat?

**Comment by Coneboi** [comment]
Couldn't answer that
