### ISSUE TITLE
Is the EPs / LPs sheet going to be added back to one of the docs?

### ISSUE THREAD

**Issue by Clbsfn** [MCatalog/Genres#28]
I'm not sure if this is the right place to ask about this, but I'm wondering if this sheet was forgotten, as it hasn't been added to either of the two documents yet, and it wasn't mentioned in the strawpoll about deleting sheets.

As one of the main editors on Monstercat's wikipedia page, I found the MCatalog's EPs / LPs sheet to be very convenient as it enabled me to quickly access an organized chart of info on Monstercat's EPs and LPs. I hope that it will be returned soon to either the main MCatalog or the Extra sheet. If anyone knows what happened to this sheet, or if there's a reason it's been removed for now, it would be great if you could give me some information about it.

**Comment by cartert54** [comment]
To be honest with you we jumped the gun and deleted the entire sheet...  Didn't think anyone got any use out of it.

I hope looking at EPs/LPs through bandcamp is fine with you for now.

**Comment by Clbsfn** [comment]
Okay, thanks for letting me know. I guess i could just use the monstercat wiki.
