### ISSUE TITLE
TwoThirds - Daydreamer (feat. Bijou)

### ISSUE THREAD

**Issue by cartert54** [MCatalog/Genres#34]

**Comment by DylanMorrissey** [comment]
trip-hop

**Comment by cartert54** [comment]
Could it be dubstep of some kind?  Otherwise yeah I agree with trip hop.

**Comment by DylanMorrissey** [comment]
yes it could also be liquid/melodic dubstep

**Comment by DylanMorrissey** [comment]
im changing it to trip-hop, melodic dubstep
