### ISSUE TITLE
Inconsistency on Haywyre - Dichotomy (Soft Mix)

### ISSUE THREAD

**Issue by Clbsfn** [MCatalog/Genres#35]
The track is labeled Future Bass, but the color is that of Glitch Hop. Should the genre label be changed to Glitch Hop, or should the color be changed to Future Bass? Or should the color be kept, and the genre changed to "Glitch Hop / Future Bass"?

**Comment by cartert54** [comment]
It was glitch hop before the overhaul so that's what's it's being changed to (for now).
