### ISSUE TITLE
PIXL - Sadbot

### ISSUE THREAD

**Issue by cartert54** [MCatalog/Genres#6]

**Comment by DylanMorrissey** [comment]
breaks / liquid dubstep (main genre is dubstep so purple color)

**Comment by DylanMorrissey** [comment]
i said breaks / liquid dubstep with dubstep color not breaks / dubstep with breaks color

**Comment by cartert54** [comment]
I know...but we've always used the first genre's color for the entire release

**Comment by DylanMorrissey** [comment]
that's wrong; the genre that comes first is not always the primary genre

**Comment by DylanMorrissey** [comment]
what do u mean theres no breaks

**Comment by Coneboi** [comment]
Textbook future garage

**Comment by DylanMorrissey** [comment]
um... what...

**Comment by Coneboi** [comment]
Half time, two step, odd, drum beat. 140 bpm, off kilter melody. Well, at least the non-dubstep sections

**Comment by DylanMorrissey** [comment]
nothing odd or irregular about the drum beat... it's a standard breakbeat
with the snares on 2 and 4

**Comment by DylanMorrissey** [comment]
i guess dubstep is better in place of liquid dubstep
